### ISSUE TITLE
Milestone: Give & accept a grant for an issue

### ISSUE THREAD

**Issue by dhalsim** [nostrize/extension#1]
Milestone issue for all the features involved for giving and receiving a bitcoin reward/grant

- [ ] [Parent: Issue Page](#5)
- [ ] [Parent: Issues Page](#6)
- [ ] [Paying & Accepting the reward](#2)
